
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
public class TicTac extends javax.swing.JFrame {

    /**
     * Creates new form TicTac
     */
    public TicTac() {
        initComponents();
    }

    int clicked = 0;
    boolean jButton_1Flag = true;
    boolean jButton_2Flag = true;
    boolean jButton_3Flag = true;
    boolean jButton_4Flag = true;
    boolean jButton_5Flag = true;
    boolean jButton_6Flag = true;
    boolean jButton_7Flag = true;
    boolean jButton_8Flag = true;
    boolean jButton_9Flag = true;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel_heading = new javax.swing.JLabel();
        jButton_8 = new javax.swing.JButton();
        jButton_3 = new javax.swing.JButton();
        jButton_7 = new javax.swing.JButton();
        jButton_1 = new javax.swing.JButton();
        jButton_4 = new javax.swing.JButton();
        jButton_9 = new javax.swing.JButton();
        jButton_5 = new javax.swing.JButton();
        jButton_2 = new javax.swing.JButton();
        jButton_6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButton8.setText("jButton1");

        jButton10.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 700));
        setPreferredSize(new java.awt.Dimension(425, 410));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(409, 311));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_heading.setFont(new java.awt.Font("Monospaced", 3, 23)); // NOI18N
        jLabel_heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_heading.setText("Tic-Tac-Toe");
        jPanel1.add(jLabel_heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        jButton_8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_8MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 130, 80));

        jButton_3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 130, 80));

        jButton_7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_7MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, 80));

        jButton_1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 80));

        jButton_4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, 80));

        jButton_9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_9MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 130, 80));

        jButton_5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_5MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 130, 80));

        jButton_2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 130, 80));

        jButton_6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_6MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 130, 80));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Play Again");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_1MouseClicked
        // TODO add your handling code here:
        
        if(jButton_1Flag){
         
            clicked++;
        if(clicked%2 == 0) {
            jButton_1.setLabel("O");
            jButton_1.setEnabled(false);
            jButton_1Flag = false;
            
        }
        else{
            jButton_1.setLabel("X");
            jButton_1.setEnabled(false);
            jButton_1Flag = false;   
        }
        }
        checkWinner();
    }//GEN-LAST:event_jButton_1MouseClicked

    private void jButton_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_2MouseClicked
        // TODO add your handling code here:
        if(jButton_2Flag){
         
            clicked++;
        if(clicked%2 == 0) {
            jButton_2.setLabel("O");
            jButton_2.setEnabled(false);
            jButton_2Flag = false;
            
        }
        else{
            jButton_2.setLabel("X");
            jButton_2.setEnabled(false);
            jButton_2Flag = false;   
        }
        }
        checkWinner();
    }//GEN-LAST:event_jButton_2MouseClicked

    private void jButton_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_3MouseClicked
        // TODO add your handling code here:
        if(jButton_3Flag){
         
            clicked++;
        if(clicked%2 == 0) {
            jButton_3.setLabel("O");
            jButton_3.setEnabled(false);
            jButton_3Flag = false;
            
        }
        else{
            jButton_3.setLabel("X");
            jButton_3.setEnabled(false);
            jButton_3Flag = false;   
        }
        }
        checkWinner();
    }//GEN-LAST:event_jButton_3MouseClicked

    private void jButton_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_4MouseClicked
        // TODO add your handling code here:
        if(jButton_4Flag){
         
            clicked++;
        if(clicked%2 == 0) {
            jButton_4.setLabel("O");
            jButton_4.setEnabled(false);
            jButton_4Flag = false;
            
        }
        else{
            jButton_4.setLabel("X");
            jButton_4.setEnabled(false);
            jButton_4Flag = false;   
        }
        }
        checkWinner();
    }//GEN-LAST:event_jButton_4MouseClicked

    private void jButton_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_5MouseClicked
        // TODO add your handling code here:
        if(jButton_5Flag){
         
            clicked++;
        if(clicked%2 == 0) {
            jButton_5.setLabel("O");
            jButton_5.setEnabled(false);
            jButton_5Flag = false;
            
        }
        else{
            jButton_5.setLabel("X");
            jButton_5.setEnabled(false);
            jButton_5Flag = false;   
        }
        }
        checkWinner();
    }//GEN-LAST:event_jButton_5MouseClicked

    private void jButton_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_6MouseClicked
        // TODO add your handling code here:
        if(jButton_6Flag){
         
            clicked++;
        if(clicked%2 == 0) {
            jButton_6.setLabel("O");
            jButton_6.setEnabled(false);
            jButton_6Flag = false;
            
        }
        else{
            jButton_6.setLabel("X");
            jButton_6.setEnabled(false);
            jButton_6Flag = false;   
        }
        }
        checkWinner();
    }//GEN-LAST:event_jButton_6MouseClicked

    private void jButton_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_7MouseClicked
        // TODO add your handling code here:
        if(jButton_7Flag){
         
            clicked++;
        if(clicked%2 == 0) {
            jButton_7.setLabel("O");
            jButton_7.setEnabled(false);
            jButton_7Flag = false;
            
        }
        else{
            jButton_7.setLabel("X");
            jButton_7.setEnabled(false);
            jButton_7Flag = false;   
        }
        }
        checkWinner();
    }//GEN-LAST:event_jButton_7MouseClicked

    private void jButton_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_8MouseClicked
        // TODO add your handling code here:
        if(jButton_8Flag){
         
            clicked++;
        if(clicked%2 == 0) {
            jButton_8.setLabel("O");
            jButton_8.setEnabled(false);
            jButton_8Flag = false;
            
        }
        else{
            jButton_8.setLabel("X");
            jButton_8.setEnabled(false);
            jButton_8Flag = false;   
        }
        }
        checkWinner();
    }//GEN-LAST:event_jButton_8MouseClicked

    private void jButton_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_9MouseClicked
        // TODO add your handling code here:
        if(jButton_9Flag){
         
            clicked++;
        if(clicked%2 == 0) {
            jButton_9.setLabel("O");
            jButton_9.setEnabled(false);
            jButton_9Flag = false;
            
        }
        else{
            jButton_9.setLabel("X");
            jButton_9.setEnabled(false);
            jButton_9Flag = false;   
        }
        }
        checkWinner();
    }//GEN-LAST:event_jButton_9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TicTac n = new TicTac();
        dispose();
        n.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    void checkWinner(){
        
        if ((jButton_1Flag == false) && (jButton_1.getText().equals(jButton_2.getText())) && (jButton_2.getText().equals(jButton_3.getText()))) {
            
            String value = jButton_1.getText();
             JOptionPane.showMessageDialog(this, value + " is the Winner !!!!");
        }
        else if ((jButton_4Flag == false) && (jButton_4.getText().equals(jButton_5.getText())) && (jButton_5.getText().equals(jButton_6.getText()))){
            
            String value = jButton_4.getText();
             JOptionPane.showMessageDialog(this, value + " is the Winner !!!!");
        }
        else if ((jButton_7Flag == false) && (jButton_7.getText().equals(jButton_8.getText())) && (jButton_8.getText().equals(jButton_9.getText()))){
            
            String value = jButton_7.getText();
             JOptionPane.showMessageDialog(this, value + " is the Winner !!!!");
        }
        else if ((jButton_1Flag == false) && (jButton_1.getText().equals(jButton_4.getText())) && (jButton_4.getText().equals(jButton_7.getText()))){
            
            String value = jButton_1.getText();
             JOptionPane.showMessageDialog(this, value + " is the Winner !!!!");
        }
        else if ((jButton_2Flag == false) && (jButton_2.getText().equals(jButton_5.getText())) && (jButton_5.getText().equals(jButton_8.getText()))){
            
            String value = jButton_2.getText();
             JOptionPane.showMessageDialog(this, value + " is the Winner !!!!");
        }
        else if ((jButton_3Flag == false) && (jButton_3.getText().equals(jButton_6.getText())) && (jButton_6.getText().equals(jButton_9.getText()))){
            
            String value = jButton_3.getText();
             JOptionPane.showMessageDialog(this, value + " is the Winner !!!!");
        }
        else if ((jButton_1Flag == false) && (jButton_1.getText().equals(jButton_5.getText())) && (jButton_5.getText().equals(jButton_9.getText()))){
            
            String value = jButton_1.getText();
             JOptionPane.showMessageDialog(this, value + " is the Winner !!!!");
        }
        else if ((jButton_3Flag == false) && (jButton_3.getText().equals(jButton_5.getText())) && (jButton_5.getText().equals(jButton_7.getText()))){
            
            String value = jButton_3.getText();
             JOptionPane.showMessageDialog(this, value + " is the Winner !!!!");
        }
        else if(jButton_1Flag == false && jButton_2Flag == false && jButton_3Flag == false && jButton_4Flag == false && jButton_5Flag == false && jButton_6Flag == false && jButton_7Flag == false && jButton_8Flag == false && jButton_9Flag == false){
            JOptionPane.showMessageDialog(this, "It is a Draw");
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_2;
    private javax.swing.JButton jButton_3;
    private javax.swing.JButton jButton_4;
    private javax.swing.JButton jButton_5;
    private javax.swing.JButton jButton_6;
    private javax.swing.JButton jButton_7;
    private javax.swing.JButton jButton_8;
    private javax.swing.JButton jButton_9;
    private javax.swing.JLabel jLabel_heading;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
